DB:
  DRIVER: "pgx"
  HOST: "postgres"
  PORT: 5432
  USER: "root"
  PASSWORD: "root"
  NAME: "main"
  # Допустимые значения: cache_statement; cache_describe; exec; simple_protocol
  QUERY_EXEC_MODE: "simple_protocol"
  SSL_MODE: "disable"

MONOLITH_DB:
  DRIVER: "mysql"
  HOST: "mysql"
  PORT: 3306
  USER: "root"
  PASSWORD: "root"
  NAME: "rc_main"

CLICKHOUSE:
  HOST: "clickhouse"
  PORT: 9000
  USER: "root"
  PASSWORD: "root"
  NAME: "default"
  BATCH_WAITING: "3s"

REDIS:
  HOST: "redis"
  PORT: 6379
  USERNAME: ""
  PASSWORD: ""
  PREFIX: "demo_local_"

AUTHGATE:
  HOST: "https://apigate-dev.inguru.dev/authgate"
  CACHE: 1m

LOGGER:
  ENCODING: "json"
  LEVEL: "debug"

CRON:
  IMPORT_SUBAGENT:
    START_TIME: "*/1 * * * *"
    LIMIT: 5000
  ACTIVE_SUBAGENT:
    START_TIME: "*/1 * * * *"
  ARCHIVE:
    START_TIME: "*/1 * * * *"
  START:
    START_TIME: "*/1 * * * *"
  HISTORY_CALC:
    START_TIME: "*/1 * * * *"
    LIMIT: 500
    COUNT: 15
    BATCH_SIZE: 200

METRICS:
  PREFIX: "demo_"

APP:
  SYSTEM_AGENTS: "1"
  CALC_CACHE: "5m"
