// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// IMetrics is an autogenerated mock type for the IMetrics type
type IMetrics struct {
	mock.Mock
}

// RecordExternalCall provides a mock function with given fields: dependency, operation, status, duration
func (_m *IMetrics) RecordExternalCall(dependency string, operation string, status string, duration time.Duration) {
	_m.Called(dependency, operation, status, duration)
}

// RecordHTTPRequest provides a mock function with given fields: method, path, statusCode, duration
func (_m *IMetrics) RecordHTTPRequest(method string, path string, statusCode int, duration time.Duration) {
	_m.Called(method, path, statusCode, duration)
}

// RecordNegativeKv provides a mock function with given fields: skId, value
func (_m *IMetrics) RecordNegativeKv(skId int, value float64) {
	_m.Called(skId, value)
}

// NewIMetrics creates a new instance of IMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMetrics {
	mock := &IMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
